### ISSUE TITLE
Broken Link to Australian Protective Security Policy Framework

### ISSUE THREAD

**Issue by alexwiese** [pmcau/AustralianProtectiveMarkings#95]
Link to [Australian Protective Security Policy Framework](https://www.protectivesecurity.gov.au/publications-library/policy-8-sensitive-and-classified-information) doesn't work.

![image](https://github.com/pmcau/AustralianProtectiveMarkings/assets/2103355/9102bc30-9490-48f4-a815-64199a29287b)

**Comment by SimonCropp** [comment]
fixed now. thanks for letting me know
